# Generated by Django 2.2.4 on 2019-10-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AngelFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('thumb', models.URLField()),
                ('species', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
